apiVersion: batch/v1
kind: CronJob
metadata:
  name: gflights-notifier
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: MAIL_SENDER_ADDRESS
              value: couderthomas@gmail.com
            - name: MAIL_SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mail_sender_password
                  name: gflights-notifier
            - name: MAIL_RECEIVER_ADDRESS
              value: couderthomas@gmail.com
            image: freerider/gflights-notifier:latest
            imagePullPolicy: IfNotPresent
            name: gflights-notifier
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '12 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
